language: node_js
node_js:
  - "0.10"
addons:
  code_climate:
    repo_token: 8bf65cf15dd8d5d0808a58637bf8761dcc5caa559fee311ac08702cac95e4866
after_script:
  - npm run cover
  - cat coverage/lcov.info | codeclimate
